name: Deploy APIM Public API

on:
  push:
    branches:
      - main  # Runs when code is pushed to the main branch
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy (dev/prod)"
        required: true
        default: "dev"

jobs:
  deploy-apim:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set Environment Variables
        run: |
          echo "ENVIRONMENT=${{ github.event.inputs.environment || 'dev' }}" >> $GITHUB_ENV
          echo "SUBSCRIPTION_ID=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r .subscriptionId)" >> $GITHUB_ENV
          echo "Using environment: $ENVIRONMENT"
          echo "Using subscription: $SUBSCRIPTION_ID"

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Login to Azure
        run: |
          az login --service-principal             -u ${{ secrets.AZURE_CLIENT_ID }}             -p ${{ secrets.AZURE_CLIENT_SECRET }}             --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Initialize Terraform
        run: |
          cd environments/$ENVIRONMENT
          terraform init

      - name: Plan Terraform
        run: |
          cd environments/$ENVIRONMENT
          terraform plan -out=tfplan -var="subscription_id=${{ secrets.SUBSCRIPTION_ID }}"
          

      - name: Apply Terraform (Manual Approval Required)
        run: |
          cd environments/$ENVIRONMENT
          terraform apply -auto-approve -var="subscription_id=${{ secrets.SUBSCRIPTION_ID }}"

      - name: Deploy API to APIM
        run: |
          az apim api import --resource-group my-rg             --service-name my-apim             --path sample-api             --specification-url $(cat apis/api1/definitions/openapi.yaml)



